name: CI Workflow

on:
  push:
    branches:
      - main # Runs when code is pushed to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint Python code with flake8
        run: |
          pip install flake8
          flake8 .

      - name: Build Docker image
        run: |
          docker build -t flask-task-api .

      - name: Health check with curl
        run: |
          docker run -d -p 5050:5050 --name flask-container flask-task-api
          sleep 5
          curl http://localhost:5050
          docker stop flask-container

      - name: Wait until Flask app is ready
        run: |
          for i in {1..10}; do
            curl --silent localhost:5050/tasks && break
            echo "Waiting for Flask app to be ready..."
            sleep 2
          done
