name: CI Workflow

on:
  push:
    branches:
      - main # Runs when code is pushed to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint Python code with flake8
        run: |
          pip install flake8
          flake8 .

      - name: Build Docker image
        run: |
          docker build -t flask-task-api .

      - name: Run container and wait for Flask app to be ready
        run: |
          docker run -d -p 5050:5050 --name flask-container flask-task-api

          for i in {1..10}; do
            echo "Attempt $i: Checking if Flask is up..."
            if curl --silent localhost:5050/tasks; then
              echo "✅ Flask is up!"
              break
            fi
            sleep 2
          done

          # Fail if the loop didn't break
          if [ $i -eq 10 ]; then
            echo "❌ Flask app failed to start in time." >&2
            exit 1
          fi

      - name: Stop Docker container
        run: docker stop flask-container
